### ISSUE TITLE
大佬您好，能分享下您爬取的这些数据吗

### ISSUE THREAD

**Issue by SwjtuLyp** [jerrychan807/Pinduoduo_Spiders#1]
如题

**Comment by jerrychan807** [comment]
如果你需要 我可以分享给你呀😆😆😆

**Comment by SwjtuLyp** [comment]
大佬，实在太感谢你了，能百度云盘分享吗？我加个您qq交流下吧------------------ 原始邮件 ------------------
发件人: "foolisheddy"<notifications@github.com>
发送时间: 2019年5月4日(星期六) 晚上10:51
收件人: "jerrychan807/Pinduoduo_Spiders"<Pinduoduo_Spiders@noreply.github.com>;
抄送: "SwjtuLyp"<1539331459@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jerrychan807/Pinduoduo_Spiders] 大佬您好，能分享下您爬取的这些数据吗 (#1)



如果你需要 我可以分享给你呀
 
&mdash;

**Comment by SwjtuLyp** [comment]
我的qq:1539331459------------------ 原始邮件 ------------------
发件人: "foolisheddy"<notifications@github.com>
发送时间: 2019年5月4日(星期六) 晚上10:51
收件人: "jerrychan807/Pinduoduo_Spiders"<Pinduoduo_Spiders@noreply.github.com>;
抄送: "SwjtuLyp"<1539331459@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jerrychan807/Pinduoduo_Spiders] 大佬您好，能分享下您爬取的这些数据吗 (#1)



如果你需要 我可以分享给你呀
 
&mdash;
